---
params:
  date: '2019-01-01'
  client: '[Insert Name Here]'
  desc: 'Here, describe your company and your work style. Some facts about your company will help candidates get the big picture. It’s a good idea to include brief descriptions of:\n  - Your products/services. This is particularly helpful if you’re a small company.\n  - Your mission. This is a statement or overview of your values.\n  - Your status. This helps explain your hiring need (e.g. if you’re growing your teams due to a recent funding round, or if you’re branching out into a new industry.)'
  overview: 'This is the overview of the document. It would typically highlight the findings and the relevant areas to focus on.'  
  organic_tbl: '!r mtcars'
  sem_table: '!r mtcars'
  first_res: '!r mtcars'
  terms_removed:
    - apple
    - pear
    - fruits
  rem_comment: 'When the sky is blue, the sun is out'
  terms_selected: 
    - dog
    - cat
    - bird
    - rat
  sel_comment: 'Just a dab of ranch and a fresh cow'
  plot_1_title: '[This is a title]'
  plot_1: '!r plot(mtcars)'
  tbl_1_title: '[This is a title]'
  tbl_1: '!r mtcars'
  plot_2_title: '[This is a title]'
  plot_2: '!r plot(pressure)'
  tbl_2_title: '[This is a title]'
  tbl_2: '!r mtcars'
output: 
  word_document:
   reference_docx: adword.docx
   toc_depth: 4
title: "Keyword Research and SEO"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
options(kableExtra.auto_format = FALSE)

```

-----  

#####  Date: `r params$date`  

### `r params$client`  

From the website:  
  
>  `r as.character(params$desc)`   
  
  
## Overview  
  
   
`r params$overview`  
  

##### Page Break  
  
 
### Terms Selected   {#terms_sel}

`r params$sel_comment`  

\newline
  
`r params$terms_selected`    
  
#### Search Engine Keyword Generation  
  
Information for trend results is readily available.  The most important aspect of the research phase is the keyword generation, especially with terms relevant to how others may find your services via search.  
  
```{r,results='asis'}
params$sem_table%>%
  knitr::kable(format = 'markdown')
  

```

### Terms Removed  
  
`r params$rem_comment`  

\newline

`r params$terms_removed`  
  
  
##### Page Break  
  

#### `r params$plot_1_title`   

  
  
```{r,fig.width=8,fig.height=10}

params$plot_1


```
-----  
   
   
##### Page Break  
  

#### `r params$tbl_1_title`   


```{r,results='asis'}

params$tbl_1%>%
  knitr::kable(format = 'markdown')


```
-----   


##### Page Break  
  

#### `r params$plot_2_title`   
  
  
```{r,results='asis',fig.width=8,fig.height=10}

params$plot_2  

```
-----  
  
  
##### Page Break  
  
  
#### `r params$tbl_2_title`   


```{r,results='asis'}

params$tbl_2%>%
  knitr::kable(format = 'markdown')


```


##### Page Break  


